# Generated by Django 4.0.3 on 2022-04-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=20)),
                ('info', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
