# Generated by Django 4.0.3 on 2022-04-07 05:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='staji',
            field=models.CharField(default=datetime.datetime(2022, 4, 7, 5, 24, 21, 430988, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='talim',
            field=models.CharField(default=datetime.datetime(2022, 4, 7, 5, 24, 31, 783890, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
