# Generated by Django 4.0.4 on 2022-04-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_yengliklar'),
    ]

    operations = [
        migrations.AddField(
            model_name='yengliklar',
            name='Image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
