# Generated by Django 4.0.4 on 2022-04-20 09:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_yengliklar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='info',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='staji',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='talim',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
