# Generated by Django 4.0.4 on 2022-05-10 21:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postssss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=20)),
                ('info', ckeditor.fields.RichTextField()),
                ('staji', ckeditor.fields.RichTextField()),
                ('talim', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
