# Generated by Django 4.0.4 on 2022-04-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rus', '0002_alter_postru_name_alter_postru_staji_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postru',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
