# Generated by Django 4.0.4 on 2022-04-23 21:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rus', '0003_alter_postru_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postru',
            name='info',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='postru',
            name='staji',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='postru',
            name='talim',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
