# Generated by Django 4.0.4 on 2022-04-24 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rus', '0004_alter_postru_info_alter_postru_staji_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postru',
            old_name='info',
            new_name='infoo',
        ),
        migrations.RenameField(
            model_name='postru',
            old_name='name',
            new_name='namee',
        ),
        migrations.RenameField(
            model_name='postru',
            old_name='staji',
            new_name='stajii',
        ),
        migrations.RenameField(
            model_name='postru',
            old_name='talim',
            new_name='talimm',
        ),
        migrations.RenameField(
            model_name='postru',
            old_name='tel',
            new_name='tell',
        ),
        migrations.RenameField(
            model_name='yengliklarru',
            old_name='ism',
            new_name='ismm',
        ),
        migrations.RenameField(
            model_name='yengliklarru',
            old_name='vaqt',
            new_name='vaqtt',
        ),
        migrations.RenameField(
            model_name='yengliklarru',
            old_name='yanglik',
            new_name='yanglikk',
        ),
    ]
