# Generated by Django 4.0.4 on 2022-04-24 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rus', '0005_rename_info_postru_infoo_rename_name_postru_namee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yengliklarru',
            old_name='Image',
            new_name='imagee',
        ),
    ]
