# Generated by Django 4.0.4 on 2022-04-29 10:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rus', '0007_testmodelru'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorModelru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=200)),
                ('staj_n', ckeditor.fields.RichTextField()),
                ('talim_n', ckeditor.fields.RichTextField()),
                ('images', models.ImageField(blank=True, upload_to='images/')),
                ('infos', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
