# Generated by Django 4.0.1 on 2022-05-08 17:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rus', '0008_doctormodelru'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModelruu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=200)),
                ('images', models.ImageField(blank=True, upload_to='images/')),
                ('infos', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
